# Generated by Django 2.2.1 on 2019-06-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionNodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsociacion', models.CharField(max_length=50)),
                ('nodo1', models.CharField(max_length=50)),
                ('nodo2', models.CharField(max_length=50)),
                ('nodo3', models.CharField(max_length=50)),
                ('KWs', models.CharField(max_length=50)),
                ('tipoAsociacion', models.CharField(choices=[('C.Generacion->C.Termoelectricas->C.Distribucion', 'C.Generacion->C.Termoelectricas->C.Distribucion'), ('C.Generacion->C.Distribucion', 'C.Generacion->C.Distribucion'), ('C.Termoelectricas->C.Distribucion', 'C.Termoelectricas->C.Distribucion'), ('C.Distribucion->C.Distribucion', 'C.Distribucion->C.Distribucion')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CentralesElectricas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacionGeografica', models.CharField(max_length=50)),
                ('tipoDeNodo', models.CharField(choices=[('Centrales de Generacion', 'Centrales de Generacion'), ('Centrales Termoelectricas', 'Centrales Termoelectricas'), ('Centros de Distribucion', 'Centros de Distribucion')], max_length=100)),
            ],
        ),
    ]
